### ISSUE TITLE
Błąd po naciśnięciu przycisku grupowego tp

### ISSUE THREAD

**Issue by Gracv** [pietreg/pgRandomTP#1]
Wersja minecraft 1.16.1

[22:15:34] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to pgRandomTP v1.0
java.lang.IllegalArgumentException: Cannot measure distance between world and eventy
	at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.1.jar:git-Purpur-683]
	at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.pietreg.randomtp.utils.LocationUtils.lambda$findPlayers$0(LocationUtils.java:35) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
	at net.pietreg.randomtp.utils.LocationUtils.findPlayers(LocationUtils.java:34) ~[?:?]
	at net.pietreg.randomtp.managers.TeleportManager.teleportGroup(TeleportManager.java:35) ~[?:?]
	at net.pietreg.randomtp.listeners.PlayerInteractListener.onInteract(PlayerInteractListener.java:31) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor117.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Purpur-683]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Purpur-683]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Purpur-683]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Purpur-683]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1205) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1198) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1174) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1018) ~[patched_1.16.1.jar:git-Purpur-683]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.1.jar:git-Purpur-683]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by pietreg** [comment]
Plugin nie jest przystosowany do użycia na wersjach wyższych niż 1.8.9, ale jak używasz go na 1.16 to w ciągu paru dni zrobię update pod 1.8-1.16

**Comment by pietreg** [comment]
@Gracv Trzymaj tutaj plugin nic w nim nie edytowałem bo przypomniałem sobie że robiłem taki jednej osobie, jeżeli będzie nadal ten bład to wbij na mój discord (https://dc.pietreg.pl), tutaj masz linka do pluginu (był robiony pod silnik 1.15): http://hostuje.net/file.php?id=34b1fd2838121a2c8482623d9ee179fc
